#!/usr/bin/env bash
#fixes a problem where curl 0:80 doesn't work

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/enginx/sites-enabled/default
sudo service nginx start
