#!/usr/bin/env bash
#fixes a problem where curl 0:80 doesn't work
sudo ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill "$(pgrep nginx | head -1)"
