#!/usr/bin/env bash
#displays The content of the current directory

for file in *
do

    if [[ $file != .* && $file == *-* ]];
    then
        part_after_dash=$(echo "$file" | awk -F'-' '{print $2}')
        echo "$part_after_dash"
    fi
done
