#!/usr/bin/env bash
#configuration file

Host 34.201.174.91
    IdentityFile /root/alx-system_engineering-devops/0x0B-ssh/school
    PasswordAuthentication no
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
